### ISSUE TITLE
Out of the box produces Run-Time error '1004': Application-defined or object-defined error.

### ISSUE THREAD

**Issue by user1138** [mcw0933/StackOverflowQuestion32974553#1]
After a fresh download of the branch master file, opening the file, and after clicking the "Fetch Data" button the following happens in the order shown:

1.  A message box is displayed showing the word "kaboom!".
2. After clicking the [OK] button on the message box from step 1, An error message window is shown with the following specs:

Window title: "Microsoft Visual Basic"
Window message:
```
Run-Time error '1004':
Application-defined or object-defined error
```
Window Buttons: [Continue],[End],[Debug],[Help]

3. After selecting the [Debug] button the procedure "FetchData" is shown:
```
Sub FetchData()
    Dim s As Worksheet
    Set s = Sheets("Data")
    
    s.QueryTables(1).Refresh
        
    s.Activate
End Sub
```
3. Note: with the following line highlighted:
```
s.QueryTables(1).Refresh
```

4. Subsequent runs of this code (by first reseting the VBA IDE by pressing the stop button, or by selecting [End] button from the Error message window) only produce the error message without displaying the message box.
5. Closing the document and reopening produces the same sequence of events from step 1 above.

Closing rant: (...because this situation warrants one!)
All sources for this issue have the same problems. In the latest version of Office there doesn't appear to be a way to successfully trap or hook the condition for completing the refresh of a Query either by built in commands or by hacks from any online sources, and this includes all the stackechange and stackoverflow pages and any msdn documented objects, methods, procedures, or otherwise that relate to this issue. Every variation of all of these resources have been tried and tested and not one of them works out of the box or with tweaking by recommendation from documentation or any other online resource. All that can be said is good luck to those who think they can get this to work repeatably and reliably.

**Comment by mcw0933** [comment]
Howdy - thanks for the heads up!  Can you help me get caught up to where you are?  

I'm guessing that you're trying to get some VBA code of your own hooked up to the Excel QueryTable After_Refresh event, like I was 2 years ago.  And further guessing you're running into problems using my example file as a point of reference.  Is that right?

I'm hopeful that I might be able to provide some help.  I have to be upfront though - I no longer work with or have access to the source code I originally wrote 2 years ago.  IIRC, I also ended up going with the approach in my other answer to the SO question - opening the query as a new, 2nd workbook and hooking a different event (Workbook_Open?).  

I am seeing though that my original workbook is working in Excel for Mac 15.25.1 (160826).  What version are you using?

![image](https://user-images.githubusercontent.com/750196/31853126-9dbaaebc-b651-11e7-8ddb-fe371d2318b9.png)
![image](https://user-images.githubusercontent.com/750196/31853127-a51eca58-b651-11e7-89b6-d24a90322eb7.png)

Finally - can I suggest that you reply to the StackOverflow question, or open a new question of your own, and point us there?  We'll probably do better in a forum with a wider audience.  Not sure how many people are looking at this repo ;)

**Comment by user1138** [comment]
Apologies for my rant. Too much time looking for answers without any substantial progress towards a solution tends to build a certain level of frustration that has no where to go. Thank you very much for your professional and kind response and demeanor, it was much needed. 

I just wanted to write back to let you know that I have seen your response and I am working on gathering the materials and resources to provide further information about how and why your code at the very least is taking on the "appearance" of not waiting for a refresh to complete. This will require video to show that this is happening. I need time to edit the video so that it is concise and clear.

You may be able to see this for yourself by using "Debug.Print" in place of any and all "MsgBox" methods to test this in the VBA for this github project. If you use "Debug.Print" you can see the output of "Debug.Print" long before the Queries have finished refreshing (or at least the screen being redrawn to show the refreshes completing). A MsgBox however does appear to give the illusion that the program is waiting because it is either taking longer to display a message box or message boxes are actually waiting for a refresh while "Debug.Print" messages do not seem to be waiting for refreshes.

I'm using two methods for testing weather or not the screen has completed refreshing, one is to post a Debug.Print message to the immediate window on either some process that is hooked into the refresh being completed such as after a DoEvents command or via the "WithEvents" method which yields the "..._AfterRefresh" hook in a Class module, the other is to add a value to a cell at the end of a Query table and after that table is Queried use that line and post it with a Debug.Print command if it posts a value from an earlier table then I know the query didn't finish before the Debug.Print command got to it. The earlier of these two methods of testing doesn't seem to work while the second one does so I'm suspecting this might be a screen refresh race condition rather then an actual Refresh race condition.

Hope this makes sense for now. I'll try and create some content to make a cleaner more easy to follow response when I'm not at work.

**Comment by mcw0933** [comment]
No sweat.  I remember being frustrated myself when I was initially writing the code against QueryTables.  It definitely felt to me that the event model was brittle / wonky in ways that had me questioning my sanity.  :)  

I don't know how much room there is in your codebase for modifications to the design, but here are a couple unsolicited suggestions.

1) Can you rely on a specific cell in the query result always being different each refresh?  If not, can you add a timestamp / counter / request key field that would act as a sentinel?  Then you could ignore the AfterRefresh event completely and just watch for cell changes.

2) Like I mentioned earlier, I ended up dropping this approach altogether in favor of opening the query result as a new, well-known-named workbook, and then hooking the WorkbookOpen event instead.

Both of these, sadly, boil down to "avoid using AfterRefresh, or abandon your sanity," so I completely understand your frustration.  Best of luck.
